dist: xenial
language: node_js

env:
  - MOZ_HEADLESS=1

services:
  - xvfb

addons:
  firefox: latest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
